# Generated by Django 5.1.3 on 2024-11-27 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0003_sticker_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='receipt',
        ),
        migrations.AddField(
            model_name='sticker',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 27, 14, 51, 19, 845819, tzinfo=datetime.timezone.utc), help_text='DD/MM/YYYY', null=True),
        ),
    ]
