# Generated by Django 5.1.3 on 2024-11-27 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0004_remove_sticker_receipt_sticker_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 27, 15, 16, 53, 812573, tzinfo=datetime.timezone.utc), help_text='MM/DD/YYYY', null=True),
        ),
    ]
