# Generated by Django 5.1.3 on 2024-11-27 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0011_alter_sticker_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 27, 15, 26, 31, 199121, tzinfo=datetime.timezone.utc), help_text='MM/DD/YYYY', null=True),
        ),
    ]
