# Generated by Django 5.1.3 on 2024-11-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0012_alter_sticker_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='expires',
            field=models.DateField(help_text='MM/DD/YYYY', null=True),
        ),
    ]
